### ISSUE TITLE
Requesting you to add a modification. To open link directly in App. 

### ISSUE THREAD

**Issue by sns192** [vknow360/DeepLink#3]
Hello,
Thank you for creating such a valuable extension. However, I have a modification request, that I expect you to consider and update the extension as soon as possible so that we can use it. 

When we click on the deep link, we get browser options out of which one is our app. However we want to open the link directly in our app without any options. especially when we send one signal push notification.  

How can we achieve that? 

here is the guide from one signal and google please check. I tried from my end but was receiving errors. 

link 1 - https://documentation.onesignal.com/docs/android-customizations#section-changing-the-open-action-of-a-notification

link 2 - https://developer.android.com/training/app-links/deep-linking.html

link 3 - https://github.com/OneSignal/OneSignal-Android-SDK/issues/389

I request you to check and reply as soon as possible. 

Awaiting your response. Thank you.

**Comment by vknow360** [comment]
Hi @sns192 
Sorry for replying late.
Actually, it is not possible with URLs because every browser listens to `http://` and `https://` URIs.
So the only thing available for you from my perspective is to create URIs instead of URLs.
An example can be this:
`myapp://Screen1`

Now this is different from usual deep links which are like this:
`https://example.xyz/Screen1`

The first will be only opened by your app while every browser will attempt to load second link.

**Comment by sns192** [comment]
The extension which you have made is helpful. But there are two things deep links and app links. 
your extension works for deep links and not app links.
with app links any link will directly open in app and not is any other browser. 
App links can easily be created in android studio following this guider - https://developer.android.com/training/app-links/instant-app-links

however I dont know how to do it in kodular. can you make an extension for this? it will help the entire community.

Thank you!!

**Comment by vknow360** [comment]
I'll check and let you know the possibility.
